/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import org.mindrot.jbcrypt.BCrypt;

import session.Session;
/**
 *
 * @author hapiz
 */
public class PanelProfil extends javax.swing.JPanel {

    /**
     * Creates new form PanelProfil
     */
    public PanelProfil() {
        initComponents();
        loadProfil();

        cbShowPassword.setSelected(false);

        txtPasswordLama.setEchoChar('*');

        txtPasswordBaru.setEchoChar('*');
    }
    private void loadProfil() {

        try {

        Connection c =
                Koneksi.getConnection();

        String sql =
                "SELECT * FROM users "
                + "WHERE id=?";

        PreparedStatement p =
                c.prepareStatement(sql);

        p.setInt(
                1,
                Session.idUser
        );

        ResultSet r =
                p.executeQuery();

        if(r.next()) {

            txtNama.setText(
                    r.getString("nama_lengkap")
            );

            txtUsername.setText(
                    r.getString("username")
            );

            txtNoHp.setText(
                    r.getString("no_hp")
            );

            txtAlamat.setText(
                    r.getString("alamat")
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaLengkap = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        lblNoHp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        lblAlamat = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        lblPasswordLama = new javax.swing.JLabel();
        txtPasswordLama = new javax.swing.JPasswordField();
        txtPasswordBaru = new javax.swing.JPasswordField();
        lblPasswordBaru = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        btnPassword = new javax.swing.JButton();

        lblNamaLengkap.setText("Nama Lengkap: ");

        lblUsername.setText("Username: ");

        lblNoHp.setText("No Hp: ");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        lblAlamat.setText("Alamat: ");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        lblPasswordLama.setText("Password Lama: ");

        lblPasswordBaru.setText("Password Baru: ");

        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        btnPassword.setText("Ganti Password");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaLengkap)
                            .addComponent(lblUsername)
                            .addComponent(lblNoHp)
                            .addComponent(lblAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtUsername)
                            .addComponent(txtNama)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordLama)
                            .addComponent(lblPasswordBaru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordBaru)
                            .addComponent(txtPasswordLama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPassword)
                                    .addComponent(cbShowPassword))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaLengkap)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoHp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordLama)
                    .addComponent(txtPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordBaru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPassword)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {

            String nama =
                    txtNama.getText();

            String username =
                    txtUsername.getText()
                    .toLowerCase();

            String noHp =
                    txtNoHp.getText();

            String alamat =
                    txtAlamat.getText();

            if(nama.isEmpty() ||
               username.isEmpty()) {

                JOptionPane.showMessageDialog(
                        null,
                        "Data wajib diisi"
                );

                return;
            }

            Connection c =
                    Koneksi.getConnection();

            String sql =
                    "UPDATE users SET "
                    + "nama_lengkap=?, "
                    + "username=?, "
                    + "no_hp=?, "
                    + "alamat=? "
                    + "WHERE id=?";

            PreparedStatement p =
                    c.prepareStatement(sql);

            p.setString(1, nama);

            p.setString(2, username);

            p.setString(3, noHp);

            p.setString(4, alamat);

            p.setInt(
                    5,
                    Session.idUser
            );

            p.executeUpdate();

            // UPDATE SESSION

            Session.namaLengkap = nama;

            Session.username = username;

            JOptionPane.showMessageDialog(
                    null,
                    "Profil berhasil diupdate"
            );

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        // TODO add your handling code here:
        try {

            String passwordLama =
                    txtPasswordLama.getText();

            String passwordBaru =
                    txtPasswordBaru.getText();

            if(passwordLama.isEmpty() ||
               passwordBaru.isEmpty()) {

                JOptionPane.showMessageDialog(
                        null,
                        "Password wajib diisi"
                );

                return;
            }

            Connection c =
                    Koneksi.getConnection();

            // AMBIL PASSWORD DATABASE

            String sql =
                    "SELECT password "
                    + "FROM users "
                    + "WHERE id=?";

            PreparedStatement p =
                    c.prepareStatement(sql);

            p.setInt(
                    1,
                    Session.idUser
            );

            var r =
                    p.executeQuery();

            if(r.next()) {

                String hash =
                        r.getString("password");

                // CEK PASSWORD LAMA

                boolean cocok =
                        BCrypt.checkpw(
                                passwordLama,
                                hash
                        );

                if(!cocok) {

                    JOptionPane.showMessageDialog(
                            null,
                            "Password lama salah"
                    );

                    return;
                }

                // HASH PASSWORD BARU

                String hashBaru =
                        BCrypt.hashpw(
                                passwordBaru,
                                BCrypt.gensalt()
                        );

                // UPDATE PASSWORD

                String update =
                        "UPDATE users "
                        + "SET password=? "
                        + "WHERE id=?";

                PreparedStatement pUpdate =
                        c.prepareStatement(update);

                pUpdate.setString(
                        1,
                        hashBaru
                );

                pUpdate.setInt(
                        2,
                        Session.idUser
                );

                pUpdate.executeUpdate();

                JOptionPane.showMessageDialog(
                        null,
                        "Password berhasil diubah"
                );

                txtPasswordLama.setText("");

                txtPasswordBaru.setText("");
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
         if(cbShowPassword.isSelected()) {

            txtPasswordLama.setEchoChar(
                    (char) 0
            );

            txtPasswordBaru.setEchoChar(
                    (char) 0
            );

        } else {

            txtPasswordLama.setEchoChar('*');

            txtPasswordBaru.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassword;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblNamaLengkap;
    private javax.swing.JLabel lblNoHp;
    private javax.swing.JLabel lblPasswordBaru;
    private javax.swing.JLabel lblPasswordLama;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JPasswordField txtPasswordBaru;
    private javax.swing.JPasswordField txtPasswordLama;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
