/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import session.Session;
/**
 *
 * @author hapiz
 */
public class PanelDashboardUser extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboardUser
     */
    public PanelDashboardUser() {
        initComponents();
        loadStatistik();

        loadAktivitas();
        txtAktivitas.setEditable(false);
    }
    // =====================================
    // LOAD STATISTIK
    // =====================================

    private void loadStatistik() {

        try {

            Connection c =
                    Koneksi.getConnection();

            // TOTAL PINJAMAN

            String sqlPinjam =
                    "SELECT COUNT(*) AS total "
                    + "FROM peminjaman "
                    + "WHERE user_id=?";

            PreparedStatement pPinjam =
                    c.prepareStatement(sqlPinjam);

            pPinjam.setInt(
                    1,
                    Session.idUser
            );

            ResultSet rPinjam =
                    pPinjam.executeQuery();

            if(rPinjam.next()) {

                lblTotalPinjam.setText(
                        rPinjam.getString("total")
                );
            }

            // TOTAL FAVORIT

            String sqlFavorit =
                    "SELECT COUNT(*) AS total "
                    + "FROM favorit "
                    + "WHERE user_id=?";

            PreparedStatement pFavorit =
                    c.prepareStatement(sqlFavorit);

            pFavorit.setInt(
                    1,
                    Session.idUser
            );

            ResultSet rFavorit =
                    pFavorit.executeQuery();

            if(rFavorit.next()) {

                lblTotalFavorit.setText(
                        rFavorit.getString("total")
                );
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }

    // =====================================
    // LOAD AKTIVITAS
    // =====================================

    private void loadAktivitas() {

        try {

            Connection c =
                    Koneksi.getConnection();

            String sql =
                    "SELECT b.judul, "
                    + "p.status, "
                    + "p.tanggal_pinjam "
                    + "FROM peminjaman p "
                    + "JOIN detail_peminjaman d "
                    + "ON p.id=d.peminjaman_id "
                    + "JOIN buku b "
                    + "ON d.buku_id=b.id "
                    + "WHERE p.user_id=? "
                    + "ORDER BY p.id DESC "
                    + "LIMIT 5";

            PreparedStatement p =
                    c.prepareStatement(sql);

            p.setInt(
                    1,
                    Session.idUser
            );

            ResultSet r =
                    p.executeQuery();

            txtAktivitas.setText("");

            while(r.next()) {

                txtAktivitas.append(

                        r.getString("judul")
                        + " - "

                        + r.getString("status")
                        + " ("

                        + r.getString("tanggal_pinjam")
                        + ")"

                        + "\n"
                );
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPinjam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalFavorit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAktivitas = new javax.swing.JTextArea();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Pinjam");

        lblTotalPinjam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPinjam.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Favorit");

        lblTotalFavorit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalFavorit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalFavorit.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalFavorit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalFavorit, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Aktivitas Terbaru:");

        txtAktivitas.setColumns(20);
        txtAktivitas.setRows(5);
        jScrollPane1.setViewportView(txtAktivitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalFavorit;
    private javax.swing.JLabel lblTotalPinjam;
    private javax.swing.JTextArea txtAktivitas;
    // End of variables declaration//GEN-END:variables
}
