/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import session.Session;
/**
 *
 * @author hapiz
 */
public class PanelBukuUser extends javax.swing.JPanel {

    /**
     * Creates new form PanelBukuUser
     */
    public PanelBukuUser() {
        initComponents();
        loadTable();

        // FIELD TIDAK BISA DIEDIT

        txtJudul.setEditable(false);

        txtPengarang.setEditable(false);

        txtPenerbit.setEditable(false);

        txtTahun.setEditable(false);

        txtStok.setEditable(false);

        btnPinjam.setEnabled(false);

        btnFavorit.setEnabled(false);
    }
    // =====================================
    // LOAD TABLE
    // =====================================

    private void loadTable() {

        DefaultTableModel model =
                new DefaultTableModel() {

            @Override
            public boolean isCellEditable(
                    int row,
                    int column
            ) {

                return false;
            }
        };

        model.addColumn("ID");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Stok");

        try {

            Connection c =
                    Koneksi.getConnection();

            Statement s =
                    c.createStatement();

            ResultSet r =
                    s.executeQuery(
                            "SELECT * FROM buku"
                    );

            while(r.next()) {

                model.addRow(new Object[] {

                    r.getString("id"),

                    r.getString("judul"),

                    r.getString("pengarang"),

                    r.getString("penerbit"),

                    r.getString("tahun"),

                    r.getString("stok")
                });
            }

            tableBuku.setModel(model);

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }

    // =====================================
    // CARI DATA
    // =====================================

    private void cariData() {

        DefaultTableModel model =
                new DefaultTableModel() {

            @Override
            public boolean isCellEditable(
                    int row,
                    int column
            ) {

                return false;
            }
        };

        model.addColumn("ID");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Stok");

        try {

            String keyword =
                    txtCari.getText();

            String sql =
                    "SELECT * FROM buku "
                    + "WHERE judul LIKE ? "
                    + "OR pengarang LIKE ? "
                    + "OR penerbit LIKE ?";

            Connection c =
                    Koneksi.getConnection();

            PreparedStatement p =
                    c.prepareStatement(sql);

            p.setString(
                    1,
                    "%" + keyword + "%"
            );

            p.setString(
                    2,
                    "%" + keyword + "%"
            );

            p.setString(
                    3,
                    "%" + keyword + "%"
            );

            ResultSet r =
                    p.executeQuery();

            while(r.next()) {

                model.addRow(new Object[] {

                    r.getString("id"),

                    r.getString("judul"),

                    r.getString("pengarang"),

                    r.getString("penerbit"),

                    r.getString("tahun"),

                    r.getString("stok")
                });
            }

            tableBuku.setModel(model);

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        lblJudul = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        lblPengarang = new javax.swing.JLabel();
        lblPenerbit = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JButton();
        btnFavorit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();

        lblCari.setText("Cari Buku:");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        lblJudul.setText("Judul: ");

        txtPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengarangActionPerformed(evt);
            }
        });

        txtPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitActionPerformed(evt);
            }
        });

        txtTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunActionPerformed(evt);
            }
        });

        lblPengarang.setText("Pengarang: ");

        lblPenerbit.setText("Penerbit: ");

        lblTahun.setText("Tahun:");

        lblStok.setText("Stok: ");

        btnPinjam.setText("Pinjam");
        btnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamActionPerformed(evt);
            }
        });

        btnFavorit.setText("Favorit");
        btnFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritActionPerformed(evt);
            }
        });

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTahun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPengarang)
                                                .addComponent(lblPenerbit, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(lblStok, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblCari, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(btnPinjam)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFavorit))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCari)
                                        .addComponent(txtJudul)
                                        .addComponent(txtPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                        .addComponent(txtPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                        .addComponent(txtStok, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJudul)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPengarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPenerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStok))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFavorit)
                    .addComponent(btnPinjam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengarangActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunActionPerformed

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        // TODO add your handling code here:
        try {

            int baris =
                    tableBuku.getSelectedRow();

            String idBuku =
                    tableBuku.getValueAt(baris, 0)
                    .toString();

            int stok =
                    Integer.parseInt(
                            tableBuku.getValueAt(baris, 5)
                            .toString()
                    );

            if(stok <= 0) {

                JOptionPane.showMessageDialog(
                        null,
                        "Stok buku habis"
                );

                return;
            }

            Connection c =
                    Koneksi.getConnection();

            // INSERT PEMINJAMAN

            String sqlPinjam =
                    "INSERT INTO peminjaman("
                    + "user_id,"
                    + "tanggal_pinjam,"
                    + "tanggal_kembali,"
                    + "status"
                    + ") VALUES("
                    + "?, NOW(), "
                    + "DATE_ADD(NOW(), INTERVAL 7 DAY), "
                    + "'dipinjam'"
                    + ")";

            PreparedStatement pPinjam =
                    c.prepareStatement(
                            sqlPinjam,
                            Statement.RETURN_GENERATED_KEYS
                    );

            pPinjam.setInt(
                    1,
                    Session.idUser
            );

            pPinjam.executeUpdate();

            ResultSet rs =
                    pPinjam.getGeneratedKeys();

            int idPeminjaman = 0;

            if(rs.next()) {

                idPeminjaman =
                        rs.getInt(1);
            }

            // DETAIL PEMINJAMAN

            String sqlDetail =
                    "INSERT INTO detail_peminjaman("
                    + "peminjaman_id,"
                    + "buku_id"
                    + ") VALUES(?,?)";

            PreparedStatement pDetail =
                    c.prepareStatement(sqlDetail);

            pDetail.setInt(
                    1,
                    idPeminjaman
            );

            pDetail.setString(
                    2,
                    idBuku
            );

            pDetail.executeUpdate();

            // UPDATE STOK

            String sqlStok =
                    "UPDATE buku "
                    + "SET stok=stok-1 "
                    + "WHERE id=?";

            PreparedStatement pStok =
                    c.prepareStatement(sqlStok);

            pStok.setString(
                    1,
                    idBuku
            );

            pStok.executeUpdate();

            JOptionPane.showMessageDialog(
                    null,
                    "Buku berhasil dipinjam"
            );

            loadTable();

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnPinjamActionPerformed

    private void btnFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritActionPerformed
        // TODO add your handling code here:
        try {

            int baris =
                    tableBuku.getSelectedRow();

            String idBuku =
                    tableBuku.getValueAt(baris, 0)
                    .toString();

            Connection c =
                    Koneksi.getConnection();

            String sql =
                    "INSERT INTO favorit("
                    + "user_id,"
                    + "buku_id"
                    + ") VALUES(?,?)";

            PreparedStatement p =
                    c.prepareStatement(sql);

            p.setInt(
                    1,
                    Session.idUser
            );

            p.setString(
                    2,
                    idBuku
            );

            p.executeUpdate();

            JOptionPane.showMessageDialog(
                    null,
                    "Buku ditambahkan ke favorit"
            );

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnFavoritActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        // TODO add your handling code here:
        int baris =
        tableBuku.getSelectedRow();

        txtJudul.setText(
            tableBuku.getValueAt(baris, 1)
            .toString()
        );

        txtPengarang.setText(
            tableBuku.getValueAt(baris, 2)
            .toString()
        );

        txtPenerbit.setText(
            tableBuku.getValueAt(baris, 3)
            .toString()
        );

        txtTahun.setText(
            tableBuku.getValueAt(baris, 4)
            .toString()
        );

        txtStok.setText(
            tableBuku.getValueAt(baris, 5)
            .toString()
        );

        btnPinjam.setEnabled(true);

        btnFavorit.setEnabled(true);
    }//GEN-LAST:event_tableBukuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFavorit;
    private javax.swing.JButton btnPinjam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPenerbit;
    private javax.swing.JLabel lblPengarang;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
