/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
/**
 *
 * @author hapiz
 */
public class PanelDashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboardAdmin
     */
    public PanelDashboardAdmin() {
        initComponents();
        loadStatistik();

        loadAktivitas();
        txtAktivitas.setEditable(false);
    }
    // =====================================
    // LOAD STATISTIK
    // =====================================

    private void loadStatistik() {

        try {

            Connection c =
                    Koneksi.getConnection();

            // TOTAL BUKU

            String sqlBuku =
                    "SELECT COUNT(*) AS total "
                    + "FROM buku";

            PreparedStatement pBuku =
                    c.prepareStatement(sqlBuku);

            ResultSet rBuku =
                    pBuku.executeQuery();

            if(rBuku.next()) {

                lblTotalBuku.setText(
                        rBuku.getString("total")
                );
            }

            // TOTAL USER

            String sqlUser =
                    "SELECT COUNT(*) AS total "
                    + "FROM users";

            PreparedStatement pUser =
                    c.prepareStatement(sqlUser);

            ResultSet rUser =
                    pUser.executeQuery();

            if(rUser.next()) {

                lblTotalUser.setText(
                        rUser.getString("total")
                );
            }

            // TOTAL PEMINJAMAN

            String sqlPinjam =
                    "SELECT COUNT(*) AS total "
                    + "FROM peminjaman";

            PreparedStatement pPinjam =
                    c.prepareStatement(sqlPinjam);

            ResultSet rPinjam =
                    pPinjam.executeQuery();

            if(rPinjam.next()) {

                lblTotalPinjam.setText(
                        rPinjam.getString("total")
                );
            }

            // TOTAL PENGEMBALIAN

            String sqlKembali =
                    "SELECT COUNT(*) AS total "
                    + "FROM peminjaman "
                    + "WHERE status='dikembalikan'";

            PreparedStatement pKembali =
                    c.prepareStatement(sqlKembali);

            ResultSet rKembali =
                    pKembali.executeQuery();

            if(rKembali.next()) {

                lblTotalKembali.setText(
                        rKembali.getString("total")
                );
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }

    // =====================================
    // LOAD AKTIVITAS
    // =====================================

    private void loadAktivitas() {

        try {

            Connection c =
                    Koneksi.getConnection();

            String sql =
                    "SELECT u.nama_lengkap, "
                    + "b.judul, "
                    + "p.status "
                    + "FROM peminjaman p "
                    + "JOIN users u "
                    + "ON p.user_id=u.id "
                    + "JOIN detail_peminjaman d "
                    + "ON p.id=d.peminjaman_id "
                    + "JOIN buku b "
                    + "ON d.buku_id=b.id "
                    + "ORDER BY p.id DESC "
                    + "LIMIT 5";

            PreparedStatement p =
                    c.prepareStatement(sql);

            ResultSet r =
                    p.executeQuery();

            txtAktivitas.setText("");

            while(r.next()) {

                txtAktivitas.append(

                        r.getString("nama_lengkap")
                        + " - "

                        + r.getString("status")
                        + " buku "

                        + r.getString("judul")

                        + "\n"
                );
            }

        } catch(Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTotalBuku = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalBuku = new javax.swing.JLabel();
        panelTotalUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalUser = new javax.swing.JLabel();
        panelTotalUser1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalPinjam = new javax.swing.JLabel();
        panelTotalBuku1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalKembali = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAktivitas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        panelTotalBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Buku");

        lblTotalBuku.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalBuku.setText("0");

        javax.swing.GroupLayout panelTotalBukuLayout = new javax.swing.GroupLayout(panelTotalBuku);
        panelTotalBuku.setLayout(panelTotalBukuLayout);
        panelTotalBukuLayout.setHorizontalGroup(
            panelTotalBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(lblTotalBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTotalBukuLayout.setVerticalGroup(
            panelTotalBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTotalUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total User");

        lblTotalUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalUser.setText("0");

        javax.swing.GroupLayout panelTotalUserLayout = new javax.swing.GroupLayout(panelTotalUser);
        panelTotalUser.setLayout(panelTotalUserLayout);
        panelTotalUserLayout.setHorizontalGroup(
            panelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTotalUserLayout.setVerticalGroup(
            panelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalUser, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTotalUser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Pengembalian");

        lblTotalPinjam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPinjam.setText("0");

        javax.swing.GroupLayout panelTotalUser1Layout = new javax.swing.GroupLayout(panelTotalUser1);
        panelTotalUser1.setLayout(panelTotalUser1Layout);
        panelTotalUser1Layout.setHorizontalGroup(
            panelTotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTotalUser1Layout.setVerticalGroup(
            panelTotalUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTotalBuku1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Peminjaman");

        lblTotalKembali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalKembali.setText("0");

        javax.swing.GroupLayout panelTotalBuku1Layout = new javax.swing.GroupLayout(panelTotalBuku1);
        panelTotalBuku1.setLayout(panelTotalBuku1Layout);
        panelTotalBuku1Layout.setHorizontalGroup(
            panelTotalBuku1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalBuku1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalBuku1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(lblTotalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTotalBuku1Layout.setVerticalGroup(
            panelTotalBuku1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalBuku1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtAktivitas.setColumns(20);
        txtAktivitas.setRows(5);
        jScrollPane1.setViewportView(txtAktivitas);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Aktivitas Terbaru:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelTotalBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTotalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(panelTotalUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelTotalBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTotalUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotalUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTotalBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotalBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalBuku;
    private javax.swing.JLabel lblTotalKembali;
    private javax.swing.JLabel lblTotalPinjam;
    private javax.swing.JLabel lblTotalUser;
    private javax.swing.JPanel panelTotalBuku;
    private javax.swing.JPanel panelTotalBuku1;
    private javax.swing.JPanel panelTotalUser;
    private javax.swing.JPanel panelTotalUser1;
    private javax.swing.JTextArea txtAktivitas;
    // End of variables declaration//GEN-END:variables
}
