/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;
import config.Koneksi;
import dashboard.DashboardAdmin;
import dashboard.DashboardUser;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import session.Session;
/**
 *
 * @author hapiz
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login - Perpustakaan");
        setResizable(false);
        setMinimumSize(new java.awt.Dimension(680, 480));

        // LEFT PANEL
        jPanel1.setBackground(new java.awt.Color(44, 62, 80)); 
        jLabel1.setForeground(java.awt.Color.WHITE); 
        jLabel1.setFont(jLabel1.getFont().deriveFont(Font.BOLD, 22)); 
        jLabel1.setMaximumSize(null); 
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER); 
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM); 
        jLabel1.setIconTextGap(12);

        // RIGHT PANEL - TITLE
        jLabel3.setText("Masuk");
        jLabel3.setFont(jLabel3.getFont().deriveFont(Font.BOLD, 28));
        jLabel3.setForeground(new java.awt.Color(44, 62, 80));

        // BUTTON
        txtLogin.setBackground(new java.awt.Color(24, 119, 242));
        txtLogin.setForeground(java.awt.Color.WHITE);
        txtLogin.setFont(txtLogin.getFont().deriveFont(Font.BOLD, 18));
        txtLogin.setToolTipText("Klik untuk login");

        // LINK
        LblDaftar.setForeground(new java.awt.Color(24, 119, 242));
        LblDaftar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // PLACEHOLDER
        txtUsername.putClientProperty("JTextField.placeholderText", "Masukkan username");
        txtPassword.putClientProperty("JTextField.placeholderText", "Masukkan password");

        setSize(680, 480);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        LblPassword = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        txtLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LblDaftar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblUsername.setText("Username: ");

        LblPassword.setText("Password: ");

        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLogin.setText("Login");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Belum Punya Akun?");

        LblDaftar.setText("Daftar Disini");
        LblDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDaftarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("<html>SISTEM MANAJEMEN<br>PERPUSTAKAAN</html>");
        jLabel1.setMaximumSize(new java.awt.Dimension(35, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MASUK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblPassword)
                    .addComponent(LblUsername)
                    .addComponent(cbShowPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LblDaftar))
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(LblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LblDaftar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
        try {

        // =========================
        // AMBIL INPUT
        // =========================

        String username =
                txtUsername.getText().trim();

        String password =
                String.valueOf(
                        txtPassword.getPassword()
                );

        // =========================
        // VALIDASI
        // =========================

        if(username.isEmpty() ||
           password.isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Username dan Password wajib diisi"
            );

            return;
        }

        // =========================
        // KONEKSI DATABASE
        // =========================

        Connection c =
                Koneksi.getConnection();

        // =========================
        // CEK USERNAME
        // =========================

        String sql =
                "SELECT * FROM users "
                + "WHERE username=?";

        PreparedStatement p =
                c.prepareStatement(sql);

        p.setString(1, username);

        ResultSet rs =
                p.executeQuery();

        // =========================
        // USER DITEMUKAN
        // =========================

        if(rs.next()) {

            // STATUS AKUN

            String status =
                    rs.getString("status");

            if(status.equals("nonaktif")) {

                JOptionPane.showMessageDialog(
                        null,
                        "Akun anda dinonaktifkan"
                );

                return;
            }

            // AMBIL HASH PASSWORD

            String hashPassword =
                    rs.getString("password");

            // CEK PASSWORD BCRYPT

            boolean cocok =
                    BCrypt.checkpw(
                            password,
                            hashPassword
                    );

            if(cocok) {
                Session.idUser =
            rs.getInt("id");

            Session.username =
            rs.getString("username");

            Session.role =
            rs.getString("role");

            Session.namaLengkap =
            rs.getString("nama_lengkap");
                // LOGIN BERHASIL

                JOptionPane.showMessageDialog(
                        null,
                        "Login berhasil"
                );

                // CEK ROLE

                if(Session.role.equals("admin")) {

                DashboardAdmin d =
                        new DashboardAdmin();

                d.setVisible(true);

        } else {

                DashboardUser d =
                        new DashboardUser();

                d.setVisible(true);
        }

            this.dispose();

            } else {

                JOptionPane.showMessageDialog(
                        null,
                        "Password salah"
                );
            }

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Username tidak ditemukan"
            );
        }

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Terjadi kesalahan : "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_txtLoginActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if(cbShowPassword.isSelected()) {

        txtPassword.setEchoChar((char)0);

        } else {

        txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void LblDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDaftarMouseClicked
        // TODO add your handling code here:
        Register r = new Register();

        r.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_LblDaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDaftar;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
