/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;
import config.Koneksi;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author hapiz
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Register - Perpustakaan");
        setMinimumSize(new java.awt.Dimension(500, 600));

        getContentPane().setBackground(java.awt.Color.WHITE);

        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(jLabel1.getFont().deriveFont(Font.BOLD, 36));

        java.awt.Font boldLabel = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12);
        for (javax.swing.JLabel lb : new javax.swing.JLabel[]{
            LblNama, LblUsername, LblPassword, LblPassword1,
            LblEmail, LblEmail1, LblAlamat
        }) {
            lb.setFont(boldLabel);
        }

        btnRegister.setBackground(new java.awt.Color(41, 128, 185));
        btnRegister.setForeground(java.awt.Color.WHITE);
        btnRegister.setFont(btnRegister.getFont().deriveFont(Font.BOLD, 18));
        btnRegister.setFocusPainted(false);
        btnRegister.setBorderPainted(false);

        txtKembali.setBackground(new java.awt.Color(149, 165, 166));
        txtKembali.setForeground(java.awt.Color.WHITE);
        txtKembali.setFocusPainted(false);
        txtKembali.setBorderPainted(false);
        txtKembali.setToolTipText("Kembali ke halaman login");

        txtNama.setToolTipText("Masukkan nama lengkap");
        txtUsername.setToolTipText("Buat username (minimal 4 karakter)");
        txtPassword.setToolTipText("Buat password (minimal 6 karakter, harus ada huruf dan angka)");
        txtKonfirmasi.setToolTipText("Ulangi password yang sama");
        txtEmail.setToolTipText("Masukkan alamat email yang valid");
        txtNoHP.setToolTipText("Masukkan nomor HP (mulai dengan 08)");
        txtAlamat.setToolTipText("Masukkan alamat lengkap");
        btnRegister.setToolTipText("Daftarkan akun baru");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        LblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        LblPassword = new javax.swing.JLabel();
        txtKonfirmasi = new javax.swing.JPasswordField();
        LblPassword1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        LblEmail1 = new javax.swing.JLabel();
        LblAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        cbShowPassword = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        LblNama.setText("Nama:");

        LblUsername.setText("Username: ");

        LblPassword.setText("Password: ");

        LblPassword1.setText("Konfirmasi Password:");

        LblEmail.setText("Email: ");

        LblEmail1.setText("No Hp:");

        LblAlamat.setText("Alamat: ");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("REGISTER");

        txtKembali.setText("Kembali");
        txtKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtKembali)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblNama)
                            .addComponent(LblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPassword1)
                            .addComponent(txtKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbShowPassword)
                            .addComponent(LblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmail1)
                            .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAlamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(LblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        try {

        // =========================
        // AMBIL INPUT
        // =========================

        String nama =
                txtNama.getText().trim();

        String username =
                txtUsername.getText().trim();

        String email =
                txtEmail.getText().trim();

        String nohp =
                txtNoHP.getText().trim();

        String alamat =
                txtAlamat.getText().trim();

        String password =
                String.valueOf(
                        txtPassword.getPassword()
                );

        String konfirmasi =
                String.valueOf(
                        txtKonfirmasi.getPassword()
                );

        // =========================
        // VALIDASI FIELD WAJIB
        // =========================

        if(nama.isEmpty() ||
           username.isEmpty() ||
           email.isEmpty() ||
           password.isEmpty() ||
           konfirmasi.isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Semua field wajib diisi"
            );

            return;
        }

        // =========================
        // VALIDASI USERNAME
        // =========================

        if(username.length() < 4) {

            JOptionPane.showMessageDialog(
                    null,
                    "Username minimal 4 karakter"
            );

            return;
        }

        // =========================
        // VALIDASI EMAIL
        // =========================

        String regexEmail =
                "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

        if(!email.matches(regexEmail)) {

            JOptionPane.showMessageDialog(
                    null,
                    "Format email tidak valid"
            );

            return;
        }

        // =========================
        // VALIDASI NO HP
        // =========================

        if(!nohp.isEmpty()) {

            String regexHP =
                    "^08[0-9]{8,13}$";

            if(!nohp.matches(regexHP)) {

                JOptionPane.showMessageDialog(
                        null,
                        "Nomor HP tidak valid"
                );

                return;
            }
        }

        // =========================
        // VALIDASI PASSWORD
        // =========================

        if(password.length() < 6) {

            JOptionPane.showMessageDialog(
                    null,
                    "Password minimal 6 karakter"
            );

            return;
        }

        // PASSWORD HARUS ADA ANGKA

        if(!password.matches(".*[0-9].*")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Password harus mengandung angka"
            );

            return;
        }

        // PASSWORD HARUS ADA HURUF

        if(!password.matches(".*[a-zA-Z].*")) {

            JOptionPane.showMessageDialog(
                    null,
                    "Password harus mengandung huruf"
            );

            return;
        }

        // KONFIRMASI PASSWORD

        if(!password.equals(konfirmasi)) {

            JOptionPane.showMessageDialog(
                    null,
                    "Konfirmasi password tidak cocok"
            );

            return;
        }

        // =========================
        // KONEKSI DATABASE
        // =========================

        Connection c =
                Koneksi.getConnection();

        // =========================
        // CEK USERNAME
        // =========================

        String cekUsername =
                "SELECT id FROM users "
                + "WHERE username=?";

        PreparedStatement psUsername =
                c.prepareStatement(
                        cekUsername
                );

        psUsername.setString(
                1,
                username
        );

        ResultSet rsUsername =
                psUsername.executeQuery();

        if(rsUsername.next()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Username sudah digunakan"
            );

            return;
        }

        // =========================
        // CEK EMAIL
        // =========================

        String cekEmail =
                "SELECT id FROM users "
                + "WHERE email=?";

        PreparedStatement psEmail =
                c.prepareStatement(
                        cekEmail
                );

        psEmail.setString(
                1,
                email
        );

        ResultSet rsEmail =
                psEmail.executeQuery();

        if(rsEmail.next()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Email sudah digunakan"
            );

            return;
        }

        // =========================
        // HASH PASSWORD BCRYPT
        // =========================

        String hashPassword =
                BCrypt.hashpw(
                        password,
                        BCrypt.gensalt()
                );

        // =========================
        // INSERT USER
        // =========================

        String sql =
                "INSERT INTO users("
                + "username,"
                + "password,"
                + "role,"
                + "nama_lengkap,"
                + "email,"
                + "no_hp,"
                + "alamat,"
                + "status"
                + ") VALUES(?,?,?,?,?,?,?,?)";

        PreparedStatement p =
                c.prepareStatement(sql);

        p.setString(1, username);
        p.setString(2, hashPassword);
        p.setString(3, "user");
        p.setString(4, nama);
        p.setString(5, email);
        p.setString(6, nohp);
        p.setString(7, alamat);
        p.setString(8, "aktif");

        p.executeUpdate();

        // =========================
        // NOTIFIKASI
        // =========================

        JOptionPane.showMessageDialog(
                null,
                "Register berhasil"
        );

        // =========================
        // RESET FORM
        // =========================

        txtNama.setText("");
        txtUsername.setText("");
        txtEmail.setText("");
        txtNoHP.setText("");
        txtAlamat.setText("");
        txtPassword.setText("");
        txtKonfirmasi.setText("");

        // =========================
        // PINDAH KE LOGIN
        // =========================

        Login login = new Login();

        login.setVisible(true);

        this.dispose();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Terjadi kesalahan : "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembaliActionPerformed
        // TODO add your handling code here:
        Login login = new Login();

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_txtKembaliActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if(cbShowPassword.isSelected()) {

        // TAMPILKAN PASSWORD

        txtPassword.setEchoChar((char)0);

        txtKonfirmasi.setEchoChar((char)0);

        } else {

        // SEMBUNYIKAN PASSWORD

        txtPassword.setEchoChar('*');

        txtKonfirmasi.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAlamat;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblEmail1;
    private javax.swing.JLabel LblNama;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPassword1;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JButton txtKembali;
    private javax.swing.JPasswordField txtKonfirmasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
